name: Upload Python Package to PyPI on Version Tag
on:
  push:
    tags:
      - 'v*'  # Push events to tags matching v*, i.e. v1.0, v20.15.10
jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/OpenTariff
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Update version from tag
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          VERSION=${TAG_NAME#v}
          echo "Tag: $TAG_NAME"
          echo "Using version: $VERSION"
          if [ -f "pyproject.toml" ]; then
            sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
            sed -i "s/version = '.*'/version = '$VERSION'/" pyproject.toml
            grep "version = .*$VERSION" pyproject.toml || echo "Warning: Failed to update version in pyproject.toml"
            echo "Updated pyproject.toml to version $VERSION"
          else
            echo "pyproject.toml not found"
          fi
          git diff
      
      - name: Build package
        run: |
          python -m build  # Build using pyproject.toml
          ls -la dist/
          
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1